# Generated by Django 5.2.14 on 2026-05-29 18:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento', null=True, verbose_name='nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone', max_length=128, null=True, region=None, verbose_name='telefone'),
        ),
    ]
