# Generated by Django 5.2.14 on 2026-05-29 19:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_nascimento_user_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Usuário', help_text='Username', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(default='2000-01-01', help_text='Data de nascimento', verbose_name='nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+5511999999999', help_text='Telefone', max_length=128, region=None, verbose_name='telefone'),
            preserve_default=False,
        ),
    ]
