# Generated by Django 5.2.15 on 2026-07-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_name_alter_user_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adesivo',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Aroma',
        ),
        migrations.DeleteModel(
            name='Embalagem',
        ),
        migrations.DeleteModel(
            name='Fita',
        ),
        migrations.DeleteModel(
            name='Parafina',
        ),
        migrations.DeleteModel(
            name='Pavio',
        ),
        migrations.RemoveField(
            model_name='recipiente',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='tampa',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Adesivo',
        ),
        migrations.DeleteModel(
            name='Recipiente',
        ),
        migrations.DeleteModel(
            name='Tampa',
        ),
    ]
