# Generated by Django 5.2.14 on 2026-08-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_adesivo_tipo_delete_aroma_delete_embalagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item da Compra', 'verbose_name_plural': 'Itens da Compra'},
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Carrinho'), (2, 'Finalizado'), (3, 'Pago'), (4, 'Entregue')], default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.compra'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.compra'),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
