# Generated by Django 5.2.14 on 2026-08-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pagamento_pedido_remove_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compra'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compra'),
        ),
    ]
