# Generated by Django 5.2.12 on 2026-04-04 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_embalagem_fita_produto_pedido_pagamento_itempedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='embalagem',
            options={'verbose_name': 'Embalagem', 'verbose_name_plural': 'Embalagens'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.CreateModel(
            name='Tampa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tamanho', models.CharField(max_length=10)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoproduto')),
            ],
        ),
    ]
