# Generated by Django 5.2.12 on 2026-04-04 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tipoproduto_alter_avaliacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tamanho', models.CharField(max_length=10)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoproduto')),
            ],
        ),
    ]
