# Generated by Django 5.2.14 on 2026-08-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_itenscompra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itenscompra',
            options={'verbose_name': 'Item da Compra', 'verbose_name_plural': 'Itens da Compra'},
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
