# Generated by Django 5.2.14 on 2026-09-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_itenscompra_options_delete_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenscompra',
            name='variacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.produtovariacao'),
        ),
    ]
