# Generated by Django 5.2.14 on 2026-09-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_itenscompra_variacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscompra',
            name='variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.produtovariacao'),
        ),
    ]
