# Generated by Django 5.2.12 on 2026-04-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_parafina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pavio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tamanho', models.CharField(max_length=10)),
            ],
        ),
    ]
