# Generated by Django 5.2.14 on 2026-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_compra_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='compra',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
