# Generated by Django 5.2.14 on 2026-10-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_data_compra_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_pagamento',
            field=models.IntegerField(choices=[(1, 'PIX'), (2, 'Dinheiro')], default=1),
        ),
    ]
