# Generated by Django 5.2.12 on 2026-04-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_produtovariacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtovariacao',
            options={'verbose_name': 'Produto Variação', 'verbose_name_plural': 'Produto Variações'},
        ),
    ]
