from .user import User
from .endereco import Endereco
from .avaliacao import Avaliacao
from .pedido import Pedido
from .pagamento import Pagamento
from .embalagem import Embalagem
from .item_pedido import ItemPedido
from .fita import Fita
from .produto import Produto
from .tampa import Tampa
from .tipo import TipoProduto
from .recipiente import Recipiente
from .aroma import Aroma
from .adesivo import Adesivo